
# services:
#   db:
#     image: mysql
#     restart: always
#     environment:
#       MYSQL_DATABASE: 'db'
#       # So you don't have to use root, but you can if you like
#       MYSQL_USER: 'user'
#       # You can use whatever password you like
#       MYSQL_PASSWORD: 'password'
#       # Password for root access
#       MYSQL_ROOT_PASSWORD: 'password'
#     ports:
#       # <Port exposed> : <MySQL Port running inside container>
#       - '3306:3306'
#     expose:
#       # Opens port 3306 on the container
#       - '3306'
#       # Where our data will be persisted
#     volumes:
#       - my-db:/var/lib/mysql
# # Names our volume
# volumes:
#   my-db:

# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false